# Generated by Django 5.0.1 on 2024-01-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('c_name', models.CharField(max_length=50)),
                ('c_email', models.CharField(max_length=50)),
                ('c_phno', models.CharField(max_length=50)),
                ('c_desc', models.TextField()),
                ('fbdate', models.DateField()),
                ('fbid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
