# Generated by Django 5.0.1 on 2024-01-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='c_desc',
            field=models.TextField(null=True),
        ),
    ]
