# Generated by Django 5.0.1 on 2024-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_feedback_c_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('c_name', models.CharField(max_length=50)),
                ('c_email', models.CharField(max_length=50)),
                ('c_phno', models.CharField(max_length=50)),
                ('c_desc', models.TextField(null=True)),
                ('rdate', models.DateField()),
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rtime', models.TimeField()),
                ('rppl', models.IntegerField()),
            ],
        ),
    ]
