# Generated by Django 5.0.1 on 2024-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
