# Generated by Django 5.0.2 on 2024-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reservation_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
