# Generated by Django 5.0.2 on 2024-02-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_feedback_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fb_rating',
            field=models.IntegerField(default=1),
        ),
    ]
