# Generated by Django 5.0.1 on 2024-02-04 16:11

import userauth.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=userauth.utilities.get_file_path),
        ),
    ]
